name: CI

on:
  push:
    branches: ["master"]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet test
        working-directory: src
        run: dotnet test --configuration Release

      - name: dotnet publish
        working-directory: src
        run: dotnet publish ActionTest.API/ActionTest.API.csproj --configuration Release -o ../artifacts

      - uses: actions/upload-artifact@v4
        with:
            name: actiontest-artifact
            path: artifacts/

  deploy_dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    # if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: actiontest-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure App Services'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-action-test-dev
          package: artifacts/

  deploy_prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: prod
    # if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: actiontest-artifact
          path: artifacts/

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure App Services'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: app-action-test-prod
          package: artifacts/