name: Run every 5 minute

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    name: Run every 5 minute
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello world
        run: echo "Hello, world!"