name: Secrets workflow

on:
  pull_request:
    branches: ["master"]

env:
  MY_SECRET: "my-secret-value"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "Secret is $MY_SECRET"