name: Secrets workflow

on:
  pull_request:
    branches: ["master"]

env:
  MY_VARIABLE: "my-secret-value"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "Variable is $MY_VARIABLE, Secret is ${{ secrets.SECRET_API_KEY }}"